# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# specific branch
pr:
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*

pool:
  vmImage: 'windows-latest'



steps:


- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0.x'
  inputs:
    version: 5.0.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore




- task: VSBuild@1
  inputs:
    solution: 'VaccineCredential\VaccineCredential.Api.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\VaccineCredential" /p:DeployIisAppPath="Default Web Site"'
    configuration: '$(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: Build
#  inputs:
#        projects: 'VaccineCredential/VaccineCredential.Api.csproj'
#        arguments: '--configuration $(BuildConfiguration)'





- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet build web jobs'
  inputs:
    projects: CredentialServiceJob/CredentialServiceJob.csproj

#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish web jobs'
  inputs:
    command: publish
    publishWebProjects: false
    projects: CredentialServiceJob/CredentialServiceJob.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/VaccineCredential/App_Data\jobs\continuous\CredentialServiceJob'
    zipAfterPublish: 

#Your build pipeline references an undefined variable named ‘Parameters.ArtifactName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: succeededOrFailed()

